export const ADD_STEP = "ADD_STEP";
export const ADD_STEP_LOADING = "ADD_STEP_LOADING";
export const ADD_STEP_SUCCESS = "ADD_STEP_SUCCESS";
export const ADD_STEP_ERROR = "ADD_STEP_ERROR";

export const SESSION_DATA_LOADING = "SESSION_DATA_LOADING";
export const SESSION_DATA_SUCCESS = "SESSION_DATA_SUCCESS";
export const SESSION_DATA_ERROR = "SESSION_DATA_ERROR";

export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
