export const NUM_MIN_PROBE_SESSIONS = 3;
export const NUM_CHALLENGING_ATTEMPTS_FOR_FOCUS = 3;
export const NUM_PROMPTED_ATTEMPTS_FOR_FOCUS = 3;
export const NUM_COMPLETE_ATTEMPTS_FOR_MASTERY = 3;
export const NUM_INCOMPLETE_ATTEMPTS_FOR_BOOSTER = 2;
