export const NUM_MIN_PROBE_SESSIONS = 3;
export const NUM_COMPLETE_ATTEMPTS_FOR_MASTERY = 3;
export const NUM_INCOMPLETE_ATTEMPTS_FOR_BOOSTER = 3;
export const NUM_TRAINING_SESSIONS_BETWEEN_PROBES = 12;
export const NUM_PROBE_SESSIONS_BETWEEN_TRAINING = 3;
