sudo: required

dist: bionic

language: node_js

node_js:
  - 12

before_install:
  - chmod u+x ./travis-setup.sh
  - bash ./travis-setup.sh

install:
  - npm install --g expo-cli
  - npm install

script:
  - npm run ci
