const ADD_SESSION_TYPE = 'ADD_SESSION_TYPE';
const ADD_SESSION = 'ADD_SESSION';
const ADD_USER_DATA = 'ADD_USER_DATA';
const ADD_CURR_SESSION_NMBR = 'ADD_CURR_SESSION_NMBR';

export { ADD_CURR_SESSION_NMBR, ADD_SESSION, ADD_SESSION_TYPE, ADD_USER_DATA };
